- name: install libraries
  apt: name={ { item } } state=present update_cache=yes
  with_items:
    - python3-dev
    - python3-pip
    - python-pip
    - libpq-dev
    - supervisor
    - python-passlib

- name: upgrade pip3
  pip: name=pip executable=pip3 state=latest

- name: upgrade pip
  pip: name=pip state=latest

- name: install virtualenv
  pip: name=virtualenv executable=pip3

- shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
- apt_repository: repo='deb https://get.docker.com/ubuntu docker main' state=present

- name: Install docker
  apt: name=lxc-docker state=present

- name: install docker-py
  pip: name=docker-py
